Output assets/gradient.gif
Set Shell bash
Set FontSize 22
Set Width 1000
Set Height 560
Set Padding 15
Set TypingSpeed 0
Hide
Type "./target/debug/examples/gradient"
Enter
Sleep 1s
Show
Sleep 800ms
Type "[<35;15;6M"
Sleep 700ms
Type "[<35;30;12M"
Sleep 700ms
Type "[<35;50;16M"
Sleep 700ms
Type "[<0;50;16M"
Type "[<0;50;16m"
Sleep 1500ms
Type "[<35;65;8M"
Sleep 1500ms
Type "[<35;75;20M"
Sleep 2s
